name: "Local Checkout"
description: "Minimal checkout action"
runs:
  using: "composite"
  steps:
    - name: Git Checkout
      shell: bash
      run: |
        git init
        git remote add origin https://github.com/${{ github.repository }}
        git fetch --depth=1 origin ${{ github.ref }}
        git checkout FETCH_HEAD
