name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change if your branch is not 'main'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Needed for GitHub APIs
          action: "upload"
          app_location: "/"       # Location of your index.html (root folder)
          api_location: ""        # No API
          output_location: ""     # No build output since it's just HTML
