name: Azure Static Web Apps Manual Deploy

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Local Checkout
        uses: ./.github/actions/checkout

      - name: Setup Node
        uses: actions/setup-node@v3  # Only works if not restricted, else remove

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Azure CLI Login
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure.json
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} \
                   --password ${{ secrets.AZURE_CLIENT_SECRET }} \
                   --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Static Web App
        run: |
          az staticwebapp upload \
            --name <YOUR_WEB_APP_NAME> \
            --resource-group <YOUR_RESOURCE_GROUP> \
            --source ./build \
            --token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

  close_env:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Preview Environment
        run: echo "PR closed — no preview teardown logic defined."
