name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Local Checkout
        uses: ./.github/actions/checkout

      - name: Install Node.js manually
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v
          npm -v

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      - name: Login to Azure
        run: |
          az login --service-principal \
            --username "${{ secrets.AZURE_CLIENT_ID }}" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Deploy to Azure Static Web Apps
        run: |
          az staticwebapp upload \
            --name <YOUR_WEB_APP_NAME> \
            --resource-group <YOUR_RESOURCE_GROUP_NAME> \
            --source ./build \
            --verbose

  close_env:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Teardown logic
        run: echo "Closed PR. No teardown logic implemented."
